# Generated by Django 4.2.7 on 2023-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Draft', 'Draft')], default='Pending', max_length=50),
        ),
    ]
